FROM registry.ci.openshift.org/ci/claude-ai-helpers:latest
USER 0:0

ENV EDGE_TOOLING_DIR=/opt/app-root/src/edge-tooling

# Copy over repo contents to be used with claude-ai-helpers
COPY . /opt/app-root/src/edge-tooling

WORKDIR /opt/app-root/src/edge-tooling

RUN dnf install -y skopeo && dnf clean all
RUN bash -c 'source images/install_tools.sh && install_gh_token && install_google_cloud_cli && install_python_tools'
ENV PATH="$HOME/.local/bin:$PATH"
